language: python

dist: xenial

notifications:
  email:
    recipients:
      - vivek.mahato@ucdconnect.ie

    on_success: [change]
    on_failure: [change]

python:
  - '3.8'
  -
install:
  - pip install -r requirements.txt
  - pip install pandas
script:
  - python -m unittest discover tests